name: Run CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        env: TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          PORT=${{ secrets.PORT }}
          UNSPLASH_API_KEY=${{ secrets.UNSPLASH_API_KEY }}
        run: npm run test
