name: Run CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Create env file
        run: |
          touch .env
          echo TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }} >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo UNSPLASH_API_KEY=${{ secrets.UNSPLASH_API_KEY }} >> .env
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
